# Generated by Django 2.1.3 on 2018-11-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleoficio',
            name='arquivo',
            field=models.FileField(default=1, upload_to='arquivo_oficios'),
            preserve_default=False,
        ),
    ]
